name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.2.3
  - pytest=8.3.4
  - scipy=1.12.0
  - pip=23.3.1
  - pip:
      - mlflow==2.19.0
      - wandb==0.19.2
